export const ADD_ORGAN = 'ADD_ORGAN';
export const FETCHING_ORGAN = 'FETCHING_ORGAN';
export const EDIT_ORGAN = 'EDIT_ORGAN';
export const UPDATE_ORGAN = 'UPDATE_ORGAN';
export const DELETE_ORGAN = 'DELETE_ORGAN';
export const IS_FETCHING_ORGAN = 'IS_FETCHING_ORGAN';
export const FETCH_ORGAN_FILTER = 'FETCH_ORGAN_FILTER';
export const FIND_ORGAN = 'FIND_ORGAN';
