const actions = {
  // tag
  LOAD_ALL_TAG_REQUEST: "LOAD_ALL_TAG_REQUEST",
  LOAD_ALL_TAG_SUCCESS: "LOAD_ALL_TAG_SUCCESS",
  LOAD_ALL_TAG_ERROR: "LOAD_ALL_TAG_ERROR",
  loadTags: () => ({
    type: actions.LOAD_ALL_TAG_REQUEST
  }),

  ADD_TAG_REQUEST: "ADD_TAG_REQUEST",
  ADD_TAG_SUCCESS: "ADD_TAG_SUCCESS",
  ADD_TAG_ERROR: "ADD_TAG_ERROR",
  addTag: (data_tag) => ({
    type: actions.ADD_TAG_REQUEST,
    data_tag
  }),

  CHANGE_TAG_REQUEST: "CHANGE_TAG_REQUEST",
  CHANGE_TAG_SUCCESS: "CHANGE_TAG_SUCCESS",
  CHANGE_TAG_ERROR: "CHANGE_TAG_ERROR",
  changeTag: (data_tag) => ({
    type: actions.CHANGE_TAG_REQUEST,
    data_tag
  }),

  DELETE_TAG_REQUEST: "DELETE_TAG_REQUEST",
  DELETE_TAG_SUCCESS: "DELETE_TAG_SUCCESS",
  DELETE_TAG_ERROR: "DELETE_TAG_ERROR",
  deleteTag: (id) => ({
    type: actions.DELETE_TAG_REQUEST,
    id
  }),

  // Category

  LOAD_ALL_CATEGORY_REQUEST: "LOAD_ALL_CATEGORY_REQUEST",
  LOAD_ALL_CATEGORY_SUCCESS: "LOAD_ALL_CATEGORY_SUCCESS",
  LOAD_ALL_CATEGORY_ERROR: "LOAD_ALL_CATEGORY_ERROR",
  loadCategorys: () => ({
    type: actions.LOAD_ALL_CATEGORY_REQUEST
  }),

  ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
  ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
  ADD_CATEGORY_ERROR: "ADD_CATEGORY_ERROR",
  addCategory: (data) => ({
    type: actions.ADD_CATEGORY_REQUEST,
    data
  }),

  CHANGE_CATEGORY_REQUEST: "CHANGE_CATEGORY_REQUEST",
  CHANGE_CATEGORY_SUCCESS: "CHANGE_CATEGORY_SUCCESS",
  CHANGE_CATEGORY_ERROR: "CHANGE_CATEGORY_ERROR",
  changeCategory: (data) => ({
    type: actions.CHANGE_CATEGORY_REQUEST,
    data
  }),

  DELETE_CATEGORY_REQUEST: "DELETE_CATEGORY_REQUEST",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_ERROR: "DELETE_CATEGORY_ERROR",
  deleteCategory: (id) => ({
    type: actions.DELETE_CATEGORY_REQUEST,
    id
  }),


  // Post

  LOAD_ALL_POST_REQUEST: "LOAD_ALL_POST_REQUEST",
  LOAD_ALL_POST_SUCCESS: "LOAD_ALL_POST_SUCCESS",
  LOAD_ALL_POST_ERROR: "LOAD_ALL_POST_ERROR",
  loadPosts: () => ({
    type: actions.LOAD_ALL_POST_REQUEST
  }),

  LOAD_POST_TAG_REQUEST: "LOAD_POST_TAG_REQUEST",
  LOAD_POST_TAG_SUCCESS: "LOAD_POST_TAG_SUCCESS",
  LOAD_POST_TAG_ERROR: "LOAD_POST_TAG_ERROR",
  loadPostTags: (id) => ({
    type: actions.LOAD_POST_TAG_REQUEST,
    id
  }),

  ADD_POST_REQUEST: "ADD_POST_REQUEST",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_ERROR: "ADD_POST_ERROR",
  addPost: (data) => ({
    type: actions.ADD_POST_REQUEST,
    data
  }),

  CHANGE_POST_REQUEST: "CHANGE_POST_REQUEST",
  CHANGE_POST_SUCCESS: "CHANGE_POST_SUCCESS",
  CHANGE_POST_ERROR: "CHANGE_POST_ERROR",
  changePost: (data) => ({
    type: actions.CHANGE_POST_REQUEST,
    data
  }),

  DELETE_POST_REQUEST: "DELETE_POST_REQUEST",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_ERROR: "DELETE_POST_ERROR",
  deletePost: (id) => ({
    type: actions.DELETE_POST_REQUEST,
    id
  }),
};
export default actions;
