const actions = {

  LOAD_ALL_USER_REQUEST: "LOAD_ALL_USER_REQUEST",
  LOAD_ALL_USER_SUCCESS: "LOAD_ALL_USER_SUCCESS",
  LOAD_ALL_USER_ERROR: "LOAD_ALL_USER_ERROR",
  loadAllUser: () => ({
    type: actions.LOAD_ALL_USER_REQUEST
  }),

  LOAD_ROLE_BY_USER_ID_REQUEST: "LOAD_ROLE_BY_USER_ID_REQUEST",
  LOAD_ROLE_BY_USER_ID_SUCCESS: "LOAD_ROLE_BY_USER_ID_SUCCESS",
  LOAD_ROLE_BY_USER_ID_ERROR: "LOAD_ROLE_BY_USER_ID_ERROR",
  loadRole: (user_id) => ({
    type: actions.LOAD_ROLE_BY_USER_ID_REQUEST,
    user_id
  }),

  ADD_NEW_USER_REQUEST: "ADD_NEW_USER_REQUEST",
  ADD_NEW_USER_SUCCESS: "ADD_NEW_USER_SUCCESS",
  ADD_NEW_USER_ERROR: "ADD_NEW_USER_ERROR",
  addNewUser: (data_user) => ({
    type: actions.ADD_NEW_USER_REQUEST,
    data_user
  }),

  CHANGE_PROFILE_REQUEST: "CHANGE_PROFILE_REQUEST",
  CHANGE_PROFILE_SUCCESS: "CHANGE_PROFILE_SUCCESS",
  CHANGE_PROFILE_ERROR: "CHANGE_PROFILE_ERROR",
  changeProfile: (data_user) => ({
    type: actions.CHANGE_PROFILE_REQUEST,
    data_user
  }),

  DELETE_USER_REQUEST: "DELETE_USER_REQUEST",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_ERROR: "DELETE_USER_ERROR",
  deleteUser: (user_id) => ({
    type: actions.DELETE_USER_REQUEST,
    user_id
  }),
};
export default actions;
